/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atchelper;

import ivao.IvaoServer;
import ivao.SocksProxy;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.JSpinner;
import ivao.SocksProxy;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.io.UnsupportedEncodingException;
import java.nio.charset.StandardCharsets;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author mhyst
 */
public class ATCHelperFrame extends javax.swing.JFrame {

    private static IvaoServer is;
    private static String oCallsign;
    /**
     * Creates new form ATCHelperFrame
     */
    public ATCHelperFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtVuelos = new javax.swing.JTable();
        btnCargarVuelos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfSearchCallsign = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfSearchOrigen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfSearchDestino = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfSearchFechaini = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfSearchFechafin = new javax.swing.JTextField();
        tfSearchLimpiar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtOut = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstMetar = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblAviones = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblATC = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        tfAirportICAO = new javax.swing.JTextField();
        btnAirportSearch = new javax.swing.JButton();
        tfAirportOutput = new javax.swing.JTextField();
        lblAirportInfo = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Vuelos ATC");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jtVuelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Callsign", "Tipo", "Squawk", "SID", "Nivel Inicial", "STAR", "Fase", "Completado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtVuelos.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jtVuelos);
        jtVuelos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jtVuelos.getColumnModel().getColumnCount() > 0) {
            jtVuelos.getColumnModel().getColumn(0).setMinWidth(50);
            jtVuelos.getColumnModel().getColumn(0).setPreferredWidth(70);
            jtVuelos.getColumnModel().getColumn(2).setMinWidth(40);
            jtVuelos.getColumnModel().getColumn(2).setPreferredWidth(50);
            jtVuelos.getColumnModel().getColumn(4).setMinWidth(90);
            jtVuelos.getColumnModel().getColumn(4).setPreferredWidth(100);
            jtVuelos.getColumnModel().getColumn(6).setMinWidth(90);
            jtVuelos.getColumnModel().getColumn(6).setPreferredWidth(100);
            jtVuelos.getColumnModel().getColumn(7).setMinWidth(200);
            jtVuelos.getColumnModel().getColumn(7).setPreferredWidth(250);
        }

        btnCargarVuelos.setText("Buscar vuelos");
        btnCargarVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarVuelosActionPerformed(evt);
            }
        });

        jLabel1.setText("Callsign");

        tfSearchCallsign.setPreferredSize(new java.awt.Dimension(100, 36));

        jLabel2.setText("Origen");

        tfSearchOrigen.setToolTipText("");
        tfSearchOrigen.setPreferredSize(new java.awt.Dimension(100, 36));

        jLabel3.setText("Destino");

        tfSearchDestino.setPreferredSize(new java.awt.Dimension(100, 36));

        jLabel4.setText("Fecha inicio");

        tfSearchFechaini.setPreferredSize(new java.awt.Dimension(100, 36));

        jLabel5.setText("Fecha fin");

        tfSearchFechafin.setPreferredSize(new java.awt.Dimension(100, 36));

        tfSearchLimpiar.setText("Limpiar");
        tfSearchLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tfSearchLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCargarVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1331, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(tfSearchCallsign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(tfSearchFechaini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tfSearchOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tfSearchDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(tfSearchFechafin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfSearchCallsign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfSearchOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfSearchDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfSearchFechaini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(tfSearchFechafin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCargarVuelos)
                    .addComponent(tfSearchLimpiar))
                .addGap(81, 81, 81))
        );

        jTabbedPane1.addTab("Buscar Vuelos", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1355, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 737, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Fraseología", jPanel3);

        txtOut.setColumns(20);
        txtOut.setRows(5);
        jScrollPane2.setViewportView(txtOut);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1331, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(296, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consola", jPanel4);

        lstMetar.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(lstMetar);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1331, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("METAR", jPanel5);

        tblAviones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Callsign", "Squawk", "Longitud", "Latitud", "Altitud", "Velocidad", "Origen", "Destino", "Piloto", "VID", "Asum."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblAviones);
        if (tblAviones.getColumnModel().getColumnCount() > 0) {
            tblAviones.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblAviones.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblAviones.getColumnModel().getColumn(5).setPreferredWidth(50);
            tblAviones.getColumnModel().getColumn(6).setPreferredWidth(50);
            tblAviones.getColumnModel().getColumn(7).setPreferredWidth(50);
            tblAviones.getColumnModel().getColumn(8).setMinWidth(200);
            tblAviones.getColumnModel().getColumn(9).setPreferredWidth(50);
            tblAviones.getColumnModel().getColumn(10).setPreferredWidth(50);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1331, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vuelos Cercanos", jPanel6);

        tblATC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Dependencia", "Controlador"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tblATC);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1331, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(291, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ATC", jPanel7);

        jLabel6.setText("ICAO");

        tfAirportICAO.setPreferredSize(new java.awt.Dimension(100, 36));

        btnAirportSearch.setText("Buscar aeropuerto");
        btnAirportSearch.setToolTipText("");
        btnAirportSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAirportSearchActionPerformed(evt);
            }
        });

        tfAirportOutput.setEditable(false);
        tfAirportOutput.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        tfAirportOutput.setPreferredSize(new java.awt.Dimension(200, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(tfAirportICAO, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addComponent(btnAirportSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblAirportInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(tfAirportOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 1101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfAirportICAO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAirportSearch))
                .addGap(18, 18, 18)
                .addComponent(tfAirportOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAirportInfo)
                .addContainerGap(457, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultar Aeropuertos", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarVuelosActionPerformed
        // TODO add your handling code here:
        while (jtVuelos.getRowCount() > 0) {
            ((DefaultTableModel) jtVuelos.getModel()).removeRow(0);
        }
        
        String sql = " where completo = true or completo = false";
        String callsign = tfSearchCallsign.getText();
        String origen = tfSearchOrigen.getText();
        String destino = tfSearchDestino.getText();
        String fechaini = tfSearchFechaini.getText();
        String fechafin = tfSearchFechafin.getText();
        
        if (callsign.trim().length() > 0) {
            sql += " and callsign like '%"+callsign+"%'";
        }
        if (origen.trim().length() > 0) {
            sql += " and origen = '"+origen+"'"; 
        }
        if (destino.trim().length() > 0) {
            sql += " and destino = '"+destino+"'"; 
        }
        if (fechaini.trim().length() > 0) {
            sql += " and fecha >= '"+fechaini+"'";
        }
        
        if (fechafin.trim().length() > 0) {
            sql += " and fecha < = '"+fechafin+"'";
        } 
        try {
            ArrayList<Vuelo> vuelos = database.Database.vuelos(sql);
            
            int r = 0;
            for (Vuelo v : vuelos) {
                System.out.println(v);
                Object[] row = new Object[8];
                row[0] = v.getId();
                row[1] = v.getCallsign();
                row[2] = v.getTipo();
                row[3] = v.getSquawck();
                row[4] = v.getSID();
                row[5] = v.getClimb();
                row[6] = v.getSTAR();
                row[7] = database.Database.getFase(v.getFase());
                ((DefaultTableModel) jtVuelos.getModel()).insertRow(r, row);
                r++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(ATCHelperFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnCargarVuelosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            // TODO add your handling code here:
            database.Database.getConnection().close();
        } catch (SQLException ex) {
            Logger.getLogger(ATCHelperFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        is.close();
    }//GEN-LAST:event_formWindowClosing

    private void tfSearchLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchLimpiarActionPerformed
        // TODO add your handling code here:
        tfSearchCallsign.setText("");
        tfSearchOrigen.setText("");
        tfSearchDestino.setText("");
        tfSearchFechaini.setText("");
        tfSearchFechafin.setText("");
    }//GEN-LAST:event_tfSearchLimpiarActionPerformed

    private void btnAirportSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAirportSearchActionPerformed
        // TODO add your handling code here:
        String ICAO = tfAirportICAO.getText();
        String res = "";
        
        if (ICAO != null && ICAO.length() == 4) {
            res = http.HttpAirportInfo.query(ICAO);
            if (res == null || res.length() ==  0) {
                lblAirportInfo.setText("Aeropuerto no encontrado");
            } else if (res.startsWith("Error:")) {
                lblAirportInfo.setText(res);
            } else {
                byte[] bytes = res.getBytes(StandardCharsets.UTF_8);
                res = new String(bytes, StandardCharsets.UTF_8);
            }
        } else {
            lblAirportInfo.setText("Introduzca ICAO de cuatro letras");
        }
        tfAirportOutput.setText(res);
    }//GEN-LAST:event_btnAirportSearchActionPerformed

    public JTextArea getOutput() {
        return txtOut;
    }
    
    public JList getListMetar() {
        return lstMetar;
    }
    
    public JTable getTableAviones() {
        return tblAviones;
    }
    
    public JTable getTableATC() {
        return tblATC;
    }
    
    public JTable getControlVuelos() {
        return jtVuelos;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATCHelperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATCHelperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATCHelperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATCHelperFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        oCallsign = "";

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ATCHelperFrame af = new ATCHelperFrame();
                JTable jtVuelos = af.jtVuelos;
                af.getListMetar().setModel(new DefaultListModel());
                JTable tablaAviones = af.getTableAviones();
                //af.getTableATC().setModel(new DefaultTableModel());
                JTable tablaATC = af.getTableATC();
                
                while (tablaAviones.getRowCount() > 0) {
                    ((DefaultTableModel) tablaAviones.getModel()).removeRow(0);
                }
                
                while (tablaATC.getRowCount() > 0) {
                    ((DefaultTableModel) tablaATC.getModel()).removeRow(0);
                }
                
                tablaAviones.setDefaultRenderer(Object.class, new DefaultTableCellRenderer(){
                    @Override
                    public Component getTableCellRendererComponent(JTable table,
                            Object value, boolean isSelected, boolean hasFocus, int row, int col) {

                        super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, col);

                        String callsign = (String) table.getModel().getValueAt(row, 0);
                        IvaoServer.FlightData fd = is.getAvion(callsign);
                        Color fore;
                        if (fd != null && fd.isAssumed()) {
                            if (fd.getDependenciaAsumido().equals(is.getDependencia())) {
                                fore = Color.BLUE;
                            } else {
                                fore = Color.RED;
                            }
                        } else {
                             fore = table.getForeground();
                        }

                        int status = (int) table.getModel().getValueAt(row, 5);
                        if (0 == status) {
                            setBackground(Color.lightGray);
                            setForeground(fore);
                        } else if (status < 55) {
                            setBackground(Color.YELLOW);
                            setForeground(fore);
                        } else {
                            setBackground(table.getBackground());
                            setForeground(fore);
                        }

                        try {
                            ((DefaultTableModel) table.getModel()).fireTableDataChanged();
                        } catch (Exception e) {}
                        return this;
                    }   
                });
                                        
                /*((DefaultTableModel) jtVuelos.getModel()).addTableModelListener(new TableModelListener() {
                    public void tableChanged(TableModelEvent e) {
                        int r = e.getLastRow();
                        int c = e.getColumn();
                        String data;

                        System.out.print("Vuelos update: fila - "+r+" columna - "+c);
                        try {
                            int id = (int) ((DefaultTableModel) af.jtVuelos.getModel()).getValueAt(r, 0);
                            
                            if (c == 7) {
                                Fase f = (Fase) ((DefaultTableModel) af.jtVuelos.getModel()).getValueAt(r, c);
                                data = "" + f.getId();
                            } else {
                                data = (String) ((DefaultTableModel) af.jtVuelos.getModel()).getValueAt(r, c);
                            }
                            System.out.println(" Vuelo actualizado: id vuelo: "+id+" dato: "+data);
                            database.Database.updateVuelo(id, c, data);
                        } catch (Exception e2) {
                            System.out.println(" Evento erróneo");
                        }
                    }
                });*/
                
                while (jtVuelos.getRowCount() > 0) {
                    ((DefaultTableModel) jtVuelos.getModel()).removeRow(0);
                }

                /*
                Añadimos el combobox
                */

                Vector model = new Vector();
                ArrayList<Fase> fases = new ArrayList<Fase>();
                try {
                    fases = database.Database.fasesEx();
                    
                    for (Fase f : fases) 
                        model.addElement( f );
                } catch (Exception e) {
                }

                JComboBox comboBox;

                comboBox = new JComboBox( model );
                comboBox.setRenderer( new FaseRenderer() );
                comboBox.addActionListener( new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        JComboBox comboBox = (JComboBox)e.getSource();
                        Fase item = (Fase)comboBox.getSelectedItem();
                        System.out.println( item.getId() + " : " + item.getNombre() );
                    }
                });

                TableColumn tcFase = jtVuelos.getColumnModel().getColumn(7);
                tcFase.setCellEditor(new DefaultCellEditor(comboBox));
                
                //tcFase.setCellRenderer(new FaseCellRenderer());
                    
                /*try {
                    ArrayList<Vuelo> vuelos = database.Database.vuelos();

                    int r = 0;
                    for (Vuelo v : vuelos) {
                        System.out.println(v);
                        Object[] row = new Object[8];
                        row[0] = v.getId();
                        row[1] = v.getCallsign();
                        row[2] = v.getTipo();
                        row[3] = v.getSquawck();
                        row[4] = v.getSID();
                        row[5] = v.getClimb();
                        row[6] = v.getSTAR();
                        row[7] = database.Database.getFase(v.getFase());
                        ((DefaultTableModel) jtVuelos.getModel()).insertRow(r, row);
                        r++;
                    }
                    

                    
                } catch (SQLException ex) {
                    Logger.getLogger(ATCHelperFrame.class.getName()).log(Level.SEVERE, null, ex);
                }*/
                
                is = new IvaoServer(af);
                
                af.tblAviones.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
                    @Override
                    public void valueChanged(ListSelectionEvent lse) {
                        JTable table = af.tblAviones;
                        
                        int r = table.getSelectedRow();
                        String callsign = (String) af.getTableAviones().getValueAt(r, 0);
                        
                        if (callsign.equals(oCallsign))
                            return;
                        
                        oCallsign = callsign;
                        String fpl = is.getFpl(callsign);
                        if(fpl.length() == 0) {
                            fpl = callsign+" no tiene plan de vuelo";
                            JOptionPane.showMessageDialog(null, fpl);                            
                        } else {
                            FlightPlan.show(fpl);
                        }
                    }
                });
                
                af.jtVuelos.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
                    @Override
                    public void valueChanged(ListSelectionEvent lse) {
                        JTable table = af.jtVuelos;
                        
                        if (table.getRowCount() == 0)
                            return;
                        if (lse.getValueIsAdjusting())
                            return;
                        int r = table.getSelectedRow();
                        int id = (int) table.getValueAt(r, 0);
                        String callsign = (String) table.getValueAt(r, 1);
                        
                        /*if (callsign.equals(oCallsign))
                            return;*/
                        
                        //oCallsign = callsign;
                        String fpl = "";
                        try {
                            fpl = database.Database.getFpl(id);
                        } catch (Exception e) {}
                        if(fpl.length() == 0) {
                            fpl = callsign+" no tiene plan de vuelo";
                            JOptionPane.showMessageDialog(null, fpl);                            
                        } else {
                            FlightPlan.show(fpl);
                        }
                    }
                });

                af.jPanel1.getRootPane().setDefaultButton(af.btnAirportSearch);
                af.pack();
                af.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAirportSearch;
    private javax.swing.JButton btnCargarVuelos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable jtVuelos;
    private javax.swing.JLabel lblAirportInfo;
    private javax.swing.JList<String> lstMetar;
    private javax.swing.JTable tblATC;
    private javax.swing.JTable tblAviones;
    private javax.swing.JTextField tfAirportICAO;
    private javax.swing.JTextField tfAirportOutput;
    private javax.swing.JTextField tfSearchCallsign;
    private javax.swing.JTextField tfSearchDestino;
    private javax.swing.JTextField tfSearchFechafin;
    private javax.swing.JTextField tfSearchFechaini;
    private javax.swing.JButton tfSearchLimpiar;
    private javax.swing.JTextField tfSearchOrigen;
    private javax.swing.JTextArea txtOut;
    // End of variables declaration//GEN-END:variables
}
